[package]
name = "pong-game"
version = "0.1.0"
authors = ["Marcus Ramberg <marcus.ramberg@gmail.com>"]
edition = "2018"

[[bin]]
name = "pong-game"

[dependencies]
piston = "0.40.0"
piston2d-graphics = "0.29.0"
pistoncore-glutin_window = "0.52.0"
piston2d-opengl_graphics = "0.58.0"
